//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateEmailAndPhoneCallWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-dev.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceDev {
            get {
                return ((string)(this["CRMOrgServiceDev"]));
            }
            set {
                this["CRMOrgServiceDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-test.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceTest {
            get {
                return ((string)(this["CRMOrgServiceTest"]));
            }
            set {
                this["CRMOrgServiceTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-uat.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceUAT {
            get {
                return ((string)(this["CRMOrgServiceUAT"]));
            }
            set {
                this["CRMOrgServiceUAT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVWLSCRMSQL1.US.CROWNCASTLE.COM,49869;Initial Catalog=Wireless_MSCRM" +
            ";Integrated Security=True")]
        public string WirelessCRMDB_Dev {
            get {
                return ((string)(this["WirelessCRMDB_Dev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_TST.US.CROWNCASTLE.COM,59085;Initial Catalog=Migration;Integr" +
            "ated Security=True")]
        public string MigrationDB_Test {
            get {
                return ((string)(this["MigrationDB_Test"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://org56d67cf6.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string InsideSalesOrgServ {
            get {
                return ((string)(this["InsideSalesOrgServ"]));
            }
            set {
                this["InsideSalesOrgServ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dynamics_dev_service_user@crowncastle.onmicrosoft.com")]
        public string UsernameIS {
            get {
                return ((string)(this["UsernameIS"]));
            }
            set {
                this["UsernameIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Crown@dev123")]
        public string PasswordIS {
            get {
                return ((string)(this["PasswordIS"]));
            }
            set {
                this["PasswordIS"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV3CCFCRMSQL1.US.CROWNCASTLE.COM\\DEV3CCFCRMSQL1,49843;Initial Catalo" +
            "g=CCFDEV3_MSCRM;Integrated Security=True")]
        public string CCFDEV3_MSCRMConnectionString {
            get {
                return ((string)(this["CCFDEV3_MSCRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV5CCFCRMSQL1.US.CROWNCASTLE.COM,54388;Initial Catalog=CCFDEV5_MSCRM" +
            " ;Integrated Security=True")]
        public string FiberCRMDB_UAT {
            get {
                return ((string)(this["FiberCRMDB_UAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVIHUBSQL1.US.CROWNCASTLE.COM,53895;Initial Catalog=IHUBDATA2;Integr" +
            "ated Security=True")]
        public string IHUBDATA2_DEV {
            get {
                return ((string)(this["IHUBDATA2_DEV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_TST.US.CROWNCASTLE.COM,59085;Initial Catalog=IHUBDATA2;Integr" +
            "ated Security=True")]
        public string IHUBDATA2_Test {
            get {
                return ((string)(this["IHUBDATA2_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_UAT.US.CROWNCASTLE.COM,52420;Initial Catalog=IHUBDATA2;Integr" +
            "ated Security=True")]
        public string IHUBDATA2_UAT {
            get {
                return ((string)(this["IHUBDATA2_UAT"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-stage.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceSTG {
            get {
                return ((string)(this["CRMOrgServiceSTG"]));
            }
            set {
                this["CRMOrgServiceSTG"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVIHUBSQL1.US.CROWNCASTLE.COM,53895;Initial Catalog=Migration;Integr" +
            "ated Security=True")]
        public string MigrationDB_Dev {
            get {
                return ((string)(this["MigrationDB_Dev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_UAT.US.CROWNCASTLE.COM,52420;Initial Catalog=Migration;Integr" +
            "ated Security=True")]
        public string MigrationDB_UAT {
            get {
                return ((string)(this["MigrationDB_UAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_STG.US.CROWNCASTLE.COM,51717;Initial Catalog=IHUBDATA2;Integr" +
            "ated Security=True")]
        public string IHUBDATA2_STG {
            get {
                return ((string)(this["IHUBDATA2_STG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV3CCFCRMSQL1.US.CROWNCASTLE.COM,49843;Initial Catalog=CCFDEV3_MSCRM" +
            " ;Integrated Security=True")]
        public string FiberCRMDB_Test {
            get {
                return ((string)(this["FiberCRMDB_Test"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV4CCFCRMSQL1.US.CROWNCASTLE.COM,51489;Initial Catalog=CCFDEV4_MSCRM" +
            " ;Integrated Security=True")]
        public string FiberCRMDB_STG {
            get {
                return ((string)(this["FiberCRMDB_STG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_STG.US.CROWNCASTLE.COM,51717;Initial Catalog=Migration;Integr" +
            "ated Security=True")]
        public string MigrationDB_STG {
            get {
                return ((string)(this["MigrationDB_STG"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-dev.crm.dynamics.com/")]
        public string CRMDevURI {
            get {
                return ((string)(this["CRMDevURI"]));
            }
            set {
                this["CRMDevURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-test.crm.dynamics.com/")]
        public string CRMTestURI {
            get {
                return ((string)(this["CRMTestURI"]));
            }
            set {
                this["CRMTestURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-uat.crm.dynamics.com/")]
        public string CRM_UAT_URI {
            get {
                return ((string)(this["CRM_UAT_URI"]));
            }
            set {
                this["CRM_UAT_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-stage.crm.dynamics.com/")]
        public string CRM_STG_URI {
            get {
                return ((string)(this["CRM_STG_URI"]));
            }
            set {
                this["CRM_STG_URI"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV3CCFCRMSQL1.US.CROWNCASTLE.COM,49843;Initial Catalog=CCFDEV3_MSCRM" +
            " ;Integrated Security=True")]
        public string FiberCRMDB_Dev {
            get {
                return ((string)(this["FiberCRMDB_Dev"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-mock.crm.dynamics.com/")]
        public string CRM_MOCK_URI {
            get {
                return ((string)(this["CRM_MOCK_URI"]));
            }
            set {
                this["CRM_MOCK_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle-mock.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceMock {
            get {
                return ((string)(this["CRMOrgServiceMock"]));
            }
            set {
                this["CRMOrgServiceMock"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVWLSCRMSQL1.US.CROWNCASTLE.COM,49869;Initial Catalog=WirelessDev5_M" +
            "SCRM;Integrated Security=True")]
        public string WirelessCRMDB_Test {
            get {
                return ((string)(this["WirelessCRMDB_Test"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string CRMOrgServiceProd {
            get {
                return ((string)(this["CRMOrgServiceProd"]));
            }
            set {
                this["CRMOrgServiceProd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crowncastle.crm.dynamics.com/")]
        public string CRM_Prod_URI {
            get {
                return ((string)(this["CRM_Prod_URI"]));
            }
            set {
                this["CRM_Prod_URI"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIRELESSCRMPRD.US.CROWNCASTLE.COM,52065;Initial Catalog=Wireless_MSCR" +
            "M;Integrated Security=True")]
        public string WirelessCRMDB_Prod {
            get {
                return ((string)(this["WirelessCRMDB_Prod"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_PRD.US.CROWNCASTLE.COM,54805;Initial Catalog=Migration;Integr" +
            "ated Security=True")]
        public string MigrationDB_Prod {
            get {
                return ((string)(this["MigrationDB_Prod"]));
            }
            set {
                this["MigrationDB_Prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IHUBSQL_PRD.US.CROWNCASTLE.COM,54805;Initial Catalog=IHUBDATA2;Integr" +
            "ated Security=True")]
        public string IHUBDATA2_Prod {
            get {
                return ((string)(this["IHUBDATA2_Prod"]));
            }
            set {
                this["IHUBDATA2_Prod"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CCFCRMSQLN1.US.CROWNCASTLE.COM,62215;Initial Catalog=CCFPROD_MSCRM;In" +
            "tegrated Security=True")]
        public string FiberCRMDB_Prod {
            get {
                return ((string)(this["FiberCRMDB_Prod"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ccicwireless.api.crm.dynamics.com/XRMServices/2011/Organization.svc")]
        public string InsideSalesOrgServProd {
            get {
                return ((string)(this["InsideSalesOrgServProd"]));
            }
            set {
                this["InsideSalesOrgServProd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("an4aiR?ei8aeh1h")]
        public string PasswordISProd {
            get {
                return ((string)(this["PasswordISProd"]));
            }
            set {
                this["PasswordISProd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zwlscrmmkto@us.crowncastle.com")]
        public string UsernameISProd {
            get {
                return ((string)(this["UsernameISProd"]));
            }
            set {
                this["UsernameISProd"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVWLSCRMSQL1.US.CROWNCASTLE.COM,49869;Initial Catalog=Wireless_MSCRM" +
            ";Integrated Security=True")]
        public string WirelessCRMDB_UAT {
            get {
                return ((string)(this["WirelessCRMDB_UAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVWLSCRMSQL1.US.CROWNCASTLE.COM,49869;Initial Catalog=Wireless_MSCRM" +
            ";Integrated Security=True")]
        public string WirelessCRMDB_STG {
            get {
                return ((string)(this["WirelessCRMDB_STG"]));
            }
        }
    }
}
