#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHUB2DBDC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IHUBDATA2")]
	public partial class IHUB2DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public IHUB2DBDataContext() : 
				base(global::MigrateEmailAndPhoneCallWPF.Properties.Settings.Default.IHUBDATA2_DEV, mappingSource)
		{
			OnCreated();
		}
		
		public IHUB2DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IHUB2DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IHUB2DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IHUB2DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Publish_XREF> Publish_XREFs
		{
			get
			{
				return this.GetTable<Publish_XREF>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Publish_XREF")]
	public partial class Publish_XREF
	{
		
		private System.Nullable<int> _seqid;
		
		private string _source;
		
		private string _entity_type;
		
		private string _src_sys_id;
		
		private string _is_survivor;
		
		private string _survivor_id;
		
		private string _parent_id;
		
		private string _active_flag;
		
		private string _surviving_system;
		
		private string _target_sys_id;
		
		private string _is_consolidated;
		
		public Publish_XREF()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seqid", DbType="Int")]
		public System.Nullable<int> seqid
		{
			get
			{
				return this._seqid;
			}
			set
			{
				if ((this._seqid != value))
				{
					this._seqid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="NVarChar(200)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this._source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entity_type", DbType="NVarChar(200)")]
		public string entity_type
		{
			get
			{
				return this._entity_type;
			}
			set
			{
				if ((this._entity_type != value))
				{
					this._entity_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_src_sys_id", DbType="NVarChar(100)")]
		public string src_sys_id
		{
			get
			{
				return this._src_sys_id;
			}
			set
			{
				if ((this._src_sys_id != value))
				{
					this._src_sys_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_survivor", DbType="NVarChar(20)")]
		public string is_survivor
		{
			get
			{
				return this._is_survivor;
			}
			set
			{
				if ((this._is_survivor != value))
				{
					this._is_survivor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_survivor_id", DbType="NVarChar(100)")]
		public string survivor_id
		{
			get
			{
				return this._survivor_id;
			}
			set
			{
				if ((this._survivor_id != value))
				{
					this._survivor_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="NVarChar(100)")]
		public string parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this._parent_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active_flag", DbType="NVarChar(10)")]
		public string active_flag
		{
			get
			{
				return this._active_flag;
			}
			set
			{
				if ((this._active_flag != value))
				{
					this._active_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surviving_system", DbType="NVarChar(200)")]
		public string surviving_system
		{
			get
			{
				return this._surviving_system;
			}
			set
			{
				if ((this._surviving_system != value))
				{
					this._surviving_system = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target_sys_id", DbType="NVarChar(36)")]
		public string target_sys_id
		{
			get
			{
				return this._target_sys_id;
			}
			set
			{
				if ((this._target_sys_id != value))
				{
					this._target_sys_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_consolidated", DbType="NVarChar(200)")]
		public string is_consolidated
		{
			get
			{
				return this._is_consolidated;
			}
			set
			{
				if ((this._is_consolidated != value))
				{
					this._is_consolidated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
