#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDBDC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Migration")]
	public partial class MigrationDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertconsolidated_system_user(consolidated_system_user instance);
    partial void Updateconsolidated_system_user(consolidated_system_user instance);
    partial void Deleteconsolidated_system_user(consolidated_system_user instance);
    #endregion
		
		public MigrationDBDataContext() : 
				base(global::MigrateEmailAndPhoneCallWPF.Properties.Settings.Default.WirelessCRMDB_Dev, mappingSource)
		{
			OnCreated();
		}
		
		public MigrationDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MigrationDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MigrationDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MigrationDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<consolidated_system_user> consolidated_system_users
		{
			get
			{
				return this.GetTable<consolidated_system_user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.consolidated_system_user")]
	public partial class consolidated_system_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _consolidated_system_user_id;
		
		private string _cci_op_active_directory_guid;
		
		private string _cci_op_active_directory_upn;
		
		private string _cci_directory_key;
		
		private string _fiber_crm_guid;
		
		private string _msdyn_contact_guid;
		
		private string _msdyn_systemuser_guid;
		
		private System.Nullable<System.DateTime> _etl_created_timestamp;
		
		private System.Nullable<System.DateTime> _etl_modified_timesatmp;
		
		private System.Nullable<long> _cci_aim_prsn_seq_num;
		
		private string _bookable_resource_guid;
		
		private string _msdyn_systemuser_manager_guid;
		
		private System.Nullable<long> _cci_aim_mgr_prsn_seq_num;
		
		private string _cci_aim_prsn_active_flag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onconsolidated_system_user_idChanging(long value);
    partial void Onconsolidated_system_user_idChanged();
    partial void Oncci_op_active_directory_guidChanging(string value);
    partial void Oncci_op_active_directory_guidChanged();
    partial void Oncci_op_active_directory_upnChanging(string value);
    partial void Oncci_op_active_directory_upnChanged();
    partial void Oncci_directory_keyChanging(string value);
    partial void Oncci_directory_keyChanged();
    partial void Onfiber_crm_guidChanging(string value);
    partial void Onfiber_crm_guidChanged();
    partial void Onmsdyn_contact_guidChanging(string value);
    partial void Onmsdyn_contact_guidChanged();
    partial void Onmsdyn_systemuser_guidChanging(string value);
    partial void Onmsdyn_systemuser_guidChanged();
    partial void Onetl_created_timestampChanging(System.Nullable<System.DateTime> value);
    partial void Onetl_created_timestampChanged();
    partial void Onetl_modified_timesatmpChanging(System.Nullable<System.DateTime> value);
    partial void Onetl_modified_timesatmpChanged();
    partial void Oncci_aim_prsn_seq_numChanging(System.Nullable<long> value);
    partial void Oncci_aim_prsn_seq_numChanged();
    partial void Onbookable_resource_guidChanging(string value);
    partial void Onbookable_resource_guidChanged();
    partial void Onmsdyn_systemuser_manager_guidChanging(string value);
    partial void Onmsdyn_systemuser_manager_guidChanged();
    partial void Oncci_aim_mgr_prsn_seq_numChanging(System.Nullable<long> value);
    partial void Oncci_aim_mgr_prsn_seq_numChanged();
    partial void Oncci_aim_prsn_active_flagChanging(string value);
    partial void Oncci_aim_prsn_active_flagChanged();
    #endregion
		
		public consolidated_system_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consolidated_system_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long consolidated_system_user_id
		{
			get
			{
				return this._consolidated_system_user_id;
			}
			set
			{
				if ((this._consolidated_system_user_id != value))
				{
					this.Onconsolidated_system_user_idChanging(value);
					this.SendPropertyChanging();
					this._consolidated_system_user_id = value;
					this.SendPropertyChanged("consolidated_system_user_id");
					this.Onconsolidated_system_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_op_active_directory_guid", DbType="NVarChar(64)")]
		public string cci_op_active_directory_guid
		{
			get
			{
				return this._cci_op_active_directory_guid;
			}
			set
			{
				if ((this._cci_op_active_directory_guid != value))
				{
					this.Oncci_op_active_directory_guidChanging(value);
					this.SendPropertyChanging();
					this._cci_op_active_directory_guid = value;
					this.SendPropertyChanged("cci_op_active_directory_guid");
					this.Oncci_op_active_directory_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_op_active_directory_upn", DbType="NVarChar(100)")]
		public string cci_op_active_directory_upn
		{
			get
			{
				return this._cci_op_active_directory_upn;
			}
			set
			{
				if ((this._cci_op_active_directory_upn != value))
				{
					this.Oncci_op_active_directory_upnChanging(value);
					this.SendPropertyChanging();
					this._cci_op_active_directory_upn = value;
					this.SendPropertyChanged("cci_op_active_directory_upn");
					this.Oncci_op_active_directory_upnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_directory_key", DbType="NVarChar(100)")]
		public string cci_directory_key
		{
			get
			{
				return this._cci_directory_key;
			}
			set
			{
				if ((this._cci_directory_key != value))
				{
					this.Oncci_directory_keyChanging(value);
					this.SendPropertyChanging();
					this._cci_directory_key = value;
					this.SendPropertyChanged("cci_directory_key");
					this.Oncci_directory_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiber_crm_guid", DbType="NVarChar(64)")]
		public string fiber_crm_guid
		{
			get
			{
				return this._fiber_crm_guid;
			}
			set
			{
				if ((this._fiber_crm_guid != value))
				{
					this.Onfiber_crm_guidChanging(value);
					this.SendPropertyChanging();
					this._fiber_crm_guid = value;
					this.SendPropertyChanged("fiber_crm_guid");
					this.Onfiber_crm_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msdyn_contact_guid", DbType="NVarChar(64)")]
		public string msdyn_contact_guid
		{
			get
			{
				return this._msdyn_contact_guid;
			}
			set
			{
				if ((this._msdyn_contact_guid != value))
				{
					this.Onmsdyn_contact_guidChanging(value);
					this.SendPropertyChanging();
					this._msdyn_contact_guid = value;
					this.SendPropertyChanged("msdyn_contact_guid");
					this.Onmsdyn_contact_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msdyn_systemuser_guid", DbType="NVarChar(64)")]
		public string msdyn_systemuser_guid
		{
			get
			{
				return this._msdyn_systemuser_guid;
			}
			set
			{
				if ((this._msdyn_systemuser_guid != value))
				{
					this.Onmsdyn_systemuser_guidChanging(value);
					this.SendPropertyChanging();
					this._msdyn_systemuser_guid = value;
					this.SendPropertyChanged("msdyn_systemuser_guid");
					this.Onmsdyn_systemuser_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etl_created_timestamp", DbType="DateTime2")]
		public System.Nullable<System.DateTime> etl_created_timestamp
		{
			get
			{
				return this._etl_created_timestamp;
			}
			set
			{
				if ((this._etl_created_timestamp != value))
				{
					this.Onetl_created_timestampChanging(value);
					this.SendPropertyChanging();
					this._etl_created_timestamp = value;
					this.SendPropertyChanged("etl_created_timestamp");
					this.Onetl_created_timestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etl_modified_timesatmp", DbType="DateTime2")]
		public System.Nullable<System.DateTime> etl_modified_timesatmp
		{
			get
			{
				return this._etl_modified_timesatmp;
			}
			set
			{
				if ((this._etl_modified_timesatmp != value))
				{
					this.Onetl_modified_timesatmpChanging(value);
					this.SendPropertyChanging();
					this._etl_modified_timesatmp = value;
					this.SendPropertyChanged("etl_modified_timesatmp");
					this.Onetl_modified_timesatmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_aim_prsn_seq_num", DbType="BigInt")]
		public System.Nullable<long> cci_aim_prsn_seq_num
		{
			get
			{
				return this._cci_aim_prsn_seq_num;
			}
			set
			{
				if ((this._cci_aim_prsn_seq_num != value))
				{
					this.Oncci_aim_prsn_seq_numChanging(value);
					this.SendPropertyChanging();
					this._cci_aim_prsn_seq_num = value;
					this.SendPropertyChanged("cci_aim_prsn_seq_num");
					this.Oncci_aim_prsn_seq_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookable_resource_guid", DbType="NVarChar(64)")]
		public string bookable_resource_guid
		{
			get
			{
				return this._bookable_resource_guid;
			}
			set
			{
				if ((this._bookable_resource_guid != value))
				{
					this.Onbookable_resource_guidChanging(value);
					this.SendPropertyChanging();
					this._bookable_resource_guid = value;
					this.SendPropertyChanged("bookable_resource_guid");
					this.Onbookable_resource_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msdyn_systemuser_manager_guid", DbType="NVarChar(36)")]
		public string msdyn_systemuser_manager_guid
		{
			get
			{
				return this._msdyn_systemuser_manager_guid;
			}
			set
			{
				if ((this._msdyn_systemuser_manager_guid != value))
				{
					this.Onmsdyn_systemuser_manager_guidChanging(value);
					this.SendPropertyChanging();
					this._msdyn_systemuser_manager_guid = value;
					this.SendPropertyChanged("msdyn_systemuser_manager_guid");
					this.Onmsdyn_systemuser_manager_guidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_aim_mgr_prsn_seq_num", DbType="BigInt")]
		public System.Nullable<long> cci_aim_mgr_prsn_seq_num
		{
			get
			{
				return this._cci_aim_mgr_prsn_seq_num;
			}
			set
			{
				if ((this._cci_aim_mgr_prsn_seq_num != value))
				{
					this.Oncci_aim_mgr_prsn_seq_numChanging(value);
					this.SendPropertyChanging();
					this._cci_aim_mgr_prsn_seq_num = value;
					this.SendPropertyChanged("cci_aim_mgr_prsn_seq_num");
					this.Oncci_aim_mgr_prsn_seq_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cci_aim_prsn_active_flag", DbType="NVarChar(10)")]
		public string cci_aim_prsn_active_flag
		{
			get
			{
				return this._cci_aim_prsn_active_flag;
			}
			set
			{
				if ((this._cci_aim_prsn_active_flag != value))
				{
					this.Oncci_aim_prsn_active_flagChanging(value);
					this.SendPropertyChanging();
					this._cci_aim_prsn_active_flag = value;
					this.SendPropertyChanged("cci_aim_prsn_active_flag");
					this.Oncci_aim_prsn_active_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
