<?xml version="1.0" encoding="utf-8"?><Database Name="WirelessDev5_MSCRM" EntityNamespace="WirelessCRMDBDC" ContextNamespace="WirelessCRMDBDC" Class="WirelessCRMDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DEVWLSCRMSQL1.US.CROWNCASTLE.COM,49869;Initial Catalog=WirelessDev5_MSCRM;Integrated Security=True" SettingsObjectName="MigrateEmailAndPhoneCallWPF.Properties.Settings" SettingsPropertyName="WirelessCRMDB_Dev" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Email" Member="Emails">
    <Type Name="Email">
      <Column Name="ParentActivityIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TemplateIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SenderMailboxIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SLAName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SLAInvokedIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningTeam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScheduledStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsWorkflowCreated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ReadReceiptRequested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Subcategory" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsBilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActualDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActualStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DirectionCode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActualEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrackingToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScheduledDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToRecipients" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DeliveryReceiptRequested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RegardingObjectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MessageId" Type="System.String" DbType="NVarChar(320)" CanBeNull="true" />
      <Column Name="RegardingObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegardingObjectIdName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MessageIdDupCheck" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Compressed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Notifications" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegardingObjectIdYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRegularActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="EmailSender" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmailSenderName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EmailSenderObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendersAccount" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SendersAccountObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderMailboxId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeliveryPriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentActivityId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="InReplyTo" Type="System.String" DbType="NVarChar(320)" CanBeNull="true" />
      <Column Name="BaseConversationIndexHash" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConversationIndex" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="CorrelationMethod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SentOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostponeEmailProcessingUntil" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityAdditionalParams" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsUnsafe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLAId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SLAInvokedId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OnHoldTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastOnHoldTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SendersAccountName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SendersAccountYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EmailSenderYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TraversedPath" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="AttachmentOpenCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConversationTrackingId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DelayedEmailSendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastOpenedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LinksClickedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReplyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmailTrackingId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FollowEmailUserPreference" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsEmailFollowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailReminderExpiryTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmailReminderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmailReminderStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmailReminderText" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ReminderActionCardId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SortDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsEmailReminderSet" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhoneCall" Member="PhoneCalls">
    <Type Name="PhoneCall">
      <Column Name="ModifiedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SLAName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SLAInvokedIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningTeam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActualEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DirectionCode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RegardingObjectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsBilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduledEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="IsWorkflowCreated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActualStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ScheduledDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subcategory" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ActualDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduledStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RegardingObjectIdName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="RegardingObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubscriptionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RegardingObjectIdYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRegularActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="LeftVoiceMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TraversedPath" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="ActivityAdditionalParams" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SLAInvokedId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OnHoldTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastOnHoldTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SLAId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SortDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityParty" Member="ActivityParties">
    <Type Name="ActivityParty">
      <Column Name="ActivityPartyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PartyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PartyObjectTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipationTypeMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddressUsed" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AddressUsedEmailColumnNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoNotEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DoNotFax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DoNotPostalMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DoNotPhone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PartyIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartyIdName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IsPartyDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExchangeEntryId" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Effort" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InstanceTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceSpecId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResourceSpecIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="ResourceSpecIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduledStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduledEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntityView" Member="EntityViews">
    <Type Name="EntityView">
      <Column Name="EntityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhysicalName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="LogicalName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CollectionName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="BaseTableName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="LogicalCollectionName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IsIntersect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSecurityIntersect" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLookupTable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EventMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLogicalEntity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCustomizable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCollaboration" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActivity" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AddressTableName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IsMappable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OwnershipTypeMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAudited" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsesFullnameConventionRules" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsParented" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntityMask" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsReplicated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsReplicationUserFiltered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsChildEntity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCustomEntity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActivityParty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsValidForAdvancedFind" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExtensionTableName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="ReportViewName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IsRequiredOffline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRenameable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntityClassName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceClassName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EntityAssembly" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceAssembly" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EntityRowId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsDuplicateCheckSupported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsImportable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsShareableAcrossOrgs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPublishable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OriginalLocalizedName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OriginalLocalizedCollectionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CanTriggerWorkflow" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WorkflowSupport" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CanBeChildInCustomRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBeInCustomEntityAssociation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBeInCustomReflexiveRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMailMergeEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RecurrenceTypeMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecurrenceBaseEntityId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsDocumentManagementEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MobileAccessLevelMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsVisibleInMobile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMultipleQueueEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AutoRouteToOwnerQueue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAuditEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsConnectionsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsReadingPaneEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMapiGridEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabledForCharts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IconLargeName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IconMediumName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IconSmallName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="NextCustomAttributeColumnNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityTypeMask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSolutionAware" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SolutionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SupportingSolutionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ComponentState" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="OverwriteTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InheritsFrom" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsInheritedFrom" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBeSecured" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyConnectionSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyDuplicateDetectionSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyMailMergeSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyQueueSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanCreateAttributes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBeRelatedEntityInRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBePrimaryEntityInRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanBeInManyToMany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanCreateForms" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanCreateCharts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanCreateViews" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyAuditSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyMobileVisibility" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentComponentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentControllingAttributeName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsManaged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyAdditionalSettings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAIRUpdated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsQuickCreateEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IntroducedVersion" Type="System.String" DbType="NVarChar(48)" CanBeNull="true" />
      <Column Name="AutoCreateAccessTeams" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBusinessProcessEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasIdsTable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsReadOnlyInMobileClient" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsVisibleInMobileClient" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyMobileClientVisibility" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyMobileClientReadOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabledForTrace" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanChangeHierarchicalRelationship" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntityHelpUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="EntityHelpUrlEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHSMEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsesBusinessDataLabelTable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsStateModelAware" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnforceStateTransitions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChangeTrackingEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanChangeTrackingBeEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanEnableSyncToExternalSearchIndex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SyncToExternalSearchIndex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntityClass" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityColor" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="EntitySetName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IsInteractionCentricEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOneNoteIntegrationEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPrivate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOfflineInMobileClient" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModifyMobileClientOffline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaysSinceRecordLastModified" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabledForExternalChannels" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanExternalChannelsBeEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOptimisticConcurrencyRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsOptimisticConcurrencyEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanOptimisticConcurrencyBeEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanOptimisticConcurrencyBeRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsKnowledgeManagementEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBPFEntity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDocumentRecommendationsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSLAEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MobileOfflineFilters" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="DataProviderId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DataSourceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExternalCollectionName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ExternalName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="IconVectorName" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="IsMergeEnabledSolutionComponent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForRetrieve" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForRetrieveMultiple" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForCreate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForUpdate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForDelete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRetrieveAuditEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRetrieveMultipleAuditEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SystemUser" Member="SystemUsers">
    <Type Name="SystemUser">
      <Column Name="ModifiedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MobileOfflineProfileIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="OrganizationIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="TerritoryIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ParentSystemUserIdName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ParentSystemUserIdYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SiteIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="EntityImage_Timestamp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EntityImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="EntityImage_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PositionIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QueueIdName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DefaultMailboxName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BusinessUnitIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="Address1_AddressTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1_City" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Composite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1_Country" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_County" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Fax" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Address1_AddressId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Address1_Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address1_Line1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Line2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Line3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address1_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address1_PostalCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_PostOfficeBox" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_ShippingMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1_StateOrProvince" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address1_Telephone1" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Address1_Telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_Telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1_UPSZone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address1_UTCOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_AddressTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_City" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Composite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2_Country" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_County" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Fax" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Address2_AddressId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Address2_Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address2_Line1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Line2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Line3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address2_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Address2_PostalCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_PostOfficeBox" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_ShippingMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2_StateOrProvince" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Address2_Telephone1" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Address2_Telephone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_Telephone3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2_UPSZone" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address2_UTCOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SystemUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TerritoryId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BusinessUnitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ParentSystemUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Salutation" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PersonalEMailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="InternalEMailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobileAlertEMail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PreferredEmailCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PreferredPhoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreferredAddressCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhotoUrl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DomainName" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="PassportLo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PassportHi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisabledReason" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GovernmentId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="Skills" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DisplayInServiceViews" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CalendarId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActiveDirectoryGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SetupUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SiteId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="WindowsLiveID" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="IncomingEmailDeliveryMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OutgoingEmailDeliveryMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessMode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InviteStatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActiveDirectoryUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YomiFullName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="YomiLastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="YomiMiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YomiFirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsIntegrationUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultFiltersPopulated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="QueueId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="EmailRouterAccessApproval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="CALType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLicensed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSyncWithDirectory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="YammerEmailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="YammerUserId" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="DefaultMailbox" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserLicenseType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityImageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsEmailAddressApprovedByO365Admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PositionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TraversedPath" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="SharePointEmailAddress" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="MobileOfflineProfileId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DefaultOdbFolderName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ApplicationIdUri" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="AzureActiveDirectoryObjectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IdentityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LatestUpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserPuid" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="mcawf_followingemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mcawf_shareoptionset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="msdyn_gdproptout" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cc_app" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cc_EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="ModifiedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SLAName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="SLAInvokedIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningTeam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsAllDayEvent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActualEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsWorkflowCreated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RegardingObjectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsBilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScheduledDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GlobalObjectId" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ScheduledStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OutlookOwnerApptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduledEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ActualStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubscriptionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subcategory" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="RegardingObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegardingObjectIdName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegardingObjectIdYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TraversedPath" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="InstanceTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedFieldsMask" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SeriesId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OriginalStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRegularActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="IsMapiPrivate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AttachmentErrors" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityAdditionalParams" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SLAId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SLAInvokedId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OnHoldTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastOnHoldTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SortDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsUnsafe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDraft" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="ModifiedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfByYomiName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="SLAName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="SLAInvokedIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="TransactionCurrencyIdName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdYomiName" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="OwnerIdDsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerIdType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwningUser" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OwningTeam" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ActualEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduledStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegardingObjectId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ScheduledDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActualStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StateCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OwningBusinessUnit" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsWorkflowCreated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Subcategory" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ScheduledEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PercentComplete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubscriptionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionNumber" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ServiceId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActualDurationMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsBilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RegardingObjectIdName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="RegardingObjectTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportSequenceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeZoneRuleVersionNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UTCConversionTimeZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverriddenCreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegardingObjectIdYomiName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CreatedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedOnBehalfBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRegularActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TransactionCurrencyId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(23,10)" CanBeNull="true" />
      <Column Name="ProcessId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="StageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TraversedPath" Type="System.String" DbType="NVarChar(1250)" CanBeNull="true" />
      <Column Name="CrmTaskAssignedUniqueId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivityAdditionalParams" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SLAId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SLAInvokedId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OnHoldTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastOnHoldTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SortDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>